# Generated by Django 5.2 on 2025-05-01 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCollecte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_souhaitee_client', models.DateField(verbose_name='Date souhaitée par le client')),
                ('contenu_declare', models.JSONField(help_text="Exemple : {'papier': 10, 'plastique': 5}", verbose_name='Contenu déclaré')),
                ('poids_estime', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poids estimé (kg)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_collecte', to='account.client')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to='account.manager')),
            ],
            options={
                'verbose_name': 'Demande de collecte',
                'verbose_name_plural': 'Demandes de collecte',
                'ordering': ['-date_souhaitee_client'],
            },
        ),
    ]
