# Generated by Django 5.2 on 2025-05-01 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('collecte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('contenu_reel', models.JSONField()),
                ('poids_estime', models.FloatField()),
                ('demande_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargements', to='collecte.demandecollecte')),
                ('logisticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargements', to='account.logisticien')),
            ],
        ),
    ]
