# Generated by Django 5.2 on 2025-05-01 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('collecte', '0002_chargement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dechet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('type_dechet', models.CharField(help_text='Ex. "serveur", "écran", etc.', max_length=100, verbose_name='Type de déchet')),
                ('etat', models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('hors_service', 'Hors service'), ('a_reparer', 'À réparer'), ('a_demanteler', 'À démanteler')], default='fonctionnel', help_text='Ex. "fonctionnel", "hors_service"', max_length=20, verbose_name='État')),
                ('quantite', models.PositiveIntegerField(help_text='Nombre d’unités', verbose_name='Quantité')),
                ('poids', models.FloatField(help_text='Poids cumulé de toutes les unités', verbose_name='Poids total (kg)')),
                ('mode_valorisation', models.CharField(choices=[('par_piece', 'Par pièce'), ('par_kg', 'Par kg'), ('autre', 'Autre')], default='par_piece', help_text='Ex. "par_piece", "par_kg"', max_length=20, verbose_name='Mode de valorisation')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix par unité ou par kg', max_digits=10, verbose_name='Prix unitaire (€)')),
                ('declare_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dechets_declares', to='account.technicien', verbose_name='Déclaré par')),
            ],
            options={
                'verbose_name': 'Déchet',
                'verbose_name_plural': 'Déchets',
                'ordering': ['type_dechet', 'etat'],
            },
        ),
    ]
