# Generated by Django 5.2 on 2025-05-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('collecte', '0003_dechet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du rapport')),
                ('poids_mesure', models.FloatField(verbose_name='Poids mesuré (kg)')),
                ('chemin_pdf', models.CharField(max_length=255, verbose_name='Chemin du PDF')),
                ('valide_par_manager', models.BooleanField(default=False, verbose_name='Validé par le manager')),
                ('dechets', models.JSONField(verbose_name='Détails des déchets triés')),
                ('chargement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='collecte.chargement', verbose_name='Chargement associé')),
                ('trie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='account.technicien', verbose_name='Technicien ayant trié')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date'],
            },
        ),
    ]
