# Generated by Django 5.1.3 on 2025-06-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0004_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dechet',
            name='chargement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dechets', to='collecte.chargement', verbose_name='Chargement associé'),
        ),
    ]
